///////////////////////////////////////////////////////////
//  Exception.h
//  Implementation of Soulib Header
//  Created on:      17-Okt-2007 17:45:04
//  Original author: Sevitec
///////////////////////////////////////////////////////////

#if !defined(EA_586073B0_669B_471c_8A98_CCBFF4D6478E__INCLUDED_)
#define EA_586073B0_669B_471c_8A98_CCBFF4D6478E__INCLUDED_

#include "Poco/Exception.h" // get system specific stuff
#include "fliplib/Fliplib.h"

namespace fliplib
{	
 
 /**
  * Redefine POCO Exceptions. !! NEUE EXCEPTION WEITER UNTEN DEFINIEREN !!
  * Implementation in Exception.cpp
  */ 
  
  
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, LogicException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, AssertionViolationException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, NullPointerException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, BugcheckException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, InvalidArgumentException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, NotImplementedException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, RangeException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, IllegalStateException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, InvalidAccessException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, SignalException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, UnhandledException)

FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, RuntimeException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, NotFoundException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, ExistsException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, TimeoutException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, SystemException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, RegularExpressionException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, LibraryLoadException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, LibraryAlreadyLoadedException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, NoThreadAvailableException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, PropertyNotSupportedException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, PoolOverflowException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, NoPermissionException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, OutOfMemoryException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, DataException)

FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, DataFormatException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, SyntaxException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, CircularReferenceException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, PathSyntaxException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, IOException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, FileException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, FileExistsException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, FileNotFoundException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, PathNotFoundException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, FileReadOnlyException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, FileAccessDeniedException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, CreateFileException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, OpenFileException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, WriteFileException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, ReadFileException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, UnknownURISchemeException)

FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, ApplicationException)
FLIPLIB_SUBCLASSING_EXCEPTION(FLIPLIB_API, BadCastException)


/**
 * Deklariert Soulib Exceptions
 */
FLIPLIB_DECLARE_EXCEPTION(FLIPLIB_API, GraphBuilderException, DataException)
FLIPLIB_DECLARE_EXCEPTION(FLIPLIB_API, ParameterException, LogicException)

}


#endif /*EA_586073B0_669B_471c_8A98_CCBFF4D6478E__INCLUDED_*/
